print ("Vamos fazer uma tabuada!!!");
n = int(input("Digite um número: "));
a = n*1;
b = n*2;
c = n*3;
d = n*4;
e = n*5;
f = n*6;
g = n*7;
h = n*8;
i = n*9;
j = n*10;

print(f"{n} x 1 = {a}");
print(f"{n} x 2 = {b}");
print(f"{n} x 3 = {c}");
print(f"{n} x 4 = {d}");
print(f"{n} x 5 = {e}");
print(f"{n} x 6 = {f}");
print(f"{n} x 7 = {g}");
print(f"{n} x 8 = {h}");
print(f"{n} x 9 = {i}");
print(f"{n} x 10 = {j}");